sector-length = 0.1    # По моим расчетам. В километрах
observation-time = 30    # Время наблюдения за сектором. В секундах
lane-count = 1    # Кол-во полос
# Желаемое разрешение видео
target-width = 1280
target-height = 720
vehicle-classes = ["bus", "car", "motobike", "road_train", "truck"]
# Коэффиценты привидения
vehicle-size-coeffs = { "car" = 1, "motorbike" = 0.5, "truck" = 1.8, "road_train" = 2.7, "bus" = 2.2 }
